# -*- coding: utf-8 -*-
"""Day-13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtXyZA-Vn9tq7P-8gxb6nCsNriDoxIxx
"""

import spacy
nlp = spacy.load("en_core_web_sm")
sentence = "NLP is amazing and fun to learn."
doc = nlp(sentence)
for token in doc:
    print(f"Word: {token.text}, POS: {token.pos_}, Tag: {token.tag_}")