# -*- coding: utf-8 -*-
"""Day-30

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UA_5Y4T4sOa4oUzsM6geK1SWUUfEOaA
"""

#Write a Python program to perform sentiment analysis on a given text using the TextBlob library. Display whether the sentiment is positive, negative, or neutral.

from textblob import TextBlob

def analyze_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity

    if polarity > 0:
        sentiment = "Positive 😊"
    elif polarity < 0:
        sentiment = "Negative 😠"
    else:
        sentiment = "Neutral 😐"

    print(f"Text: {text}")
    print(f"Polarity Score: {polarity:.2f}")
    print(f"Sentiment: {sentiment}")

texts = [
    "I love this product! It's absolutely amazing!",
    "This is the worst experience I've ever had.",
    "It's okay, nothing special."
]

# Analyze each text
for text in texts:
    print("\n" + "=" * 40)
    analyze_sentiment(text)