# -*- coding: utf-8 -*-
"""Day-28

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA0nZcCmq24frSRw28pWqrAxDoU8JtNh
"""

#Write a Python program to perform Named Entity Recognition (NER) on a given text using SpaCy. Print the entities and their types.

import spacy

nlp = spacy.load("en_core_web_sm")

text = "Elon Musk is the CEO of Tesla and SpaceX. He was born in South Africa in 1971."

doc = nlp(text)

print(f"{'Entity':<20} {'Type'}")
print("-" * 40)
for ent in doc.ents:
    print(f"{ent.text:<20} {ent.label_}")

print("\nEntity Type Descriptions:")
print(spacy.explain("PERSON"))
print(spacy.explain("ORG"))
print(spacy.explain("GPE"))
print(spacy.explain("DATE"))