# -*- coding: utf-8 -*-
"""Day-36

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4v15nrnXpeiqmQfcTURPyfFbo22WlJb
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

def text_classification(texts, labels, new_text):
    # Create a pipeline with CountVectorizer and MultinomialNB
    model = make_pipeline(CountVectorizer(), MultinomialNB())

    # Train the model
    model.fit(texts, labels)

    # Predict the category of the new text
    predicted_label = model.predict([new_text])[0]
    return predicted_label

# Example input texts and labels
texts = ["I love programming", "Python is great", "Machine learning is amazing", "Data science is the future"]
labels = ["Programming", "Programming", "AI", "AI"]

# New text to classify
new_text = "Deep learning is a subset of AI"

predicted_category = text_classification(texts, labels, new_text)
print(f"Predicted category: {predicted_category}")

