# -*- coding: utf-8 -*-
"""Day-40

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zO_V7dXnG9uMeDhQZL_pzbU8nG3QvpeX
"""

#Write a Python program to classify text using an ensemble model (`RandomForestClassifier`) from `sklearn.ensemble`.
#Use `TfidfVectorizer` to convert text into numerical format.
#Example input:
#["Buy now and win a prize", "Normal email content", "Congratulations, you won!"]




from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline

def text_classification(texts, labels, new_text):
    # Create a pipeline with TfidfVectorizer and RandomForestClassifier
    model = make_pipeline(TfidfVectorizer(), RandomForestClassifier())

    # Train the model
    model.fit(texts, labels)

    # Predict the category of the new text
    predicted_label = model.predict([new_text])[0]
    return predicted_label

texts = ["Buy now and win a prize", "Normal email content", "Congratulations, you won!"]
labels = ["Spam", "Not Spam", "Spam"]
new_text = "Claim your free reward now!"

predicted_category = text_classification(texts, labels, new_text)
print(f"Predicted category: {predicted_category}")

