# -*- coding: utf-8 -*-
"""Day-34

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EcGa9pY6d9On5JE2Y3fCoDbTAevDDkB
"""

#Write a Python program to convert a given text into a Bag of Words (BoW) representation using `CountVectorizer` from `sklearn.feature_extraction.text`.
#Also, compute the TF-IDF representation using `TfidfVectorizer`.
#Example input:
#["I love machine learning", "Machine learning is fun", "Deep learning is amazing"]


from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

def bow_tfidf_representation(texts):

    count_vectorizer = CountVectorizer()
    bow_matrix = count_vectorizer.fit_transform(texts)


    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

    print("Bag of Words (BoW) representation:")
    print(count_vectorizer.get_feature_names_out())
    print(bow_matrix.toarray())

    # Display TF-IDF
    print("\nTF-IDF representation:")
    print(tfidf_vectorizer.get_feature_names_out())
    print(tfidf_matrix.toarray())

# Example input texts
texts = ["I love machine learning", "Machine learning is fun", "Deep learning is amazing"]
bow_tfidf_representation(texts)

