# -*- coding: utf-8 -*-
"""Day-26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xP7xGfVxCsnw42hb-RibzyiTRVKFREF
"""
#Write a Python program to calculate the cosine similarity between two strings using the Scikit-learn library. You can use the 'TfidfVectorizer' class to transform the text into vectors.

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


text1 = "Natural Language Processing is fascinating."
text2 = "Natural Language Processing helps computers understand human language."

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([text1, text2])

cosine_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])

print(f"Cosine Similarity: {cosine_sim[0][0]:.4f}")