# -*- coding: utf-8 -*-
"""Day-42

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLuL5PlonM-fRl4MmZrDZhKhK7RNpME3
"""

#Write a Python program to generate a short text completion using OpenAI’s GPT model (`openai.ChatCompletion.create`).
#Use the `text-davinci-003` model to complete the sentence: "Artificial Intelligence is..."
#Note: Install OpenAI’s API package and use an API key.



from transformers import pipeline

def generate_text_completion(prompt):
    generator = pipeline("text-generation", model="gpt2")
    response = generator(prompt, max_length=50, num_return_sequences=1)
    return response[0]["generated_text"]

# Example usage
prompt = "Artificial Intelligence is"
completion = generate_text_completion(prompt)
print(f"Generated Completion: {completion}")

