# -*- coding: utf-8 -*-
"""Day-38

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9tDclkMcEhGMreE2EKYr-mDlGSjduzK
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import make_pipeline

def text_classification(texts, labels, new_text):
    # Create a pipeline with TfidfVectorizer and DecisionTreeClassifier
    model = make_pipeline(TfidfVectorizer(), DecisionTreeClassifier())

    # Train the model
    model.fit(texts, labels)

    # Predict the category of the new text
    predicted_label = model.predict([new_text])[0]
    return predicted_label

# Example input texts and labels
texts = ["Spam messages are annoying", "I won a lottery", "This is a normal message"]
labels = ["Spam", "Spam", "Not Spam"]

# New text to classify
new_text = "You have won a prize!"

# Perform classification
predicted_category = text_classification(texts, labels, new_text)
print(f"Predicted category: {predicted_category}")

